In [1]:

from google.colab import files

# Upload a ZIP file
uploaded = files.upload()

Saving iris Flower.zip to iris Flower.zip


In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


In [3]:
import os

# Directory where the contents are extracted
extracted_dir = "/content/"

# Print the contents of the extracted directory
print(os.listdir(extracted_dir))


['.config', 'iris Flower.zip', 'sample_data']


In [4]:
import pandas as pd
import zipfile
import os

# Extract the contents of the zip file
zip_file_path = "/content/iris Flower.zip"
extracted_dir = "/content/"

with zipfile.ZipFile(zip_file_path, "r") as zip_ref:
    zip_ref.extractall(extracted_dir)

# Print the contents of the extracted directory
print(os.listdir(extracted_dir))

# Load the CSV file from the extracted contents
csv_file_path = os.path.join(extracted_dir, "IRIS.csv")
your_data = pd.read_csv(csv_file_path)

['.config', 'iris Flower.zip', 'IRIS.csv', 'sample_data']


In [5]:
# Display the column names in your dataset
print(your_data.columns)


Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')


In [6]:
# Extract features (X) and target variable (y)
X = your_data.drop("species", axis=1)
y = your_data["species"]


In [7]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Load the CSV file from the extracted contents
csv_file_path = "/content/IRIS.csv"
your_data = pd.read_csv(csv_file_path)

# Extract features (X) and target variable (y)
X = your_data.drop("species", axis=1)
y = your_data["species"]

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize the features (optional but recommended for some algorithms)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Build and train the machine learning model
knn_classifier = KNeighborsClassifier(n_neighbors=3)
knn_classifier.fit(X_train, y_train)

# Make predictions on the test set
y_pred = knn_classifier.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy:.2f}')

conf_matrix = confusion_matrix(y_test, y_pred)
print(f'Confusion Matrix:\n{conf_matrix}')

class_report = classification_report(y_test, y_pred)
print(f'Classification Report:\n{class_report}')


Accuracy: 1.00
Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Classification Report:
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       1.00      1.00      1.00         9
 Iris-virginica       1.00      1.00      1.00        11

       accuracy                           1.00        30
      macro avg       1.00      1.00      1.00        30
   weighted avg       1.00      1.00      1.00        30

